name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('frontend/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install frontend dependencies
        run: bun install

      - name: Run OX Lint check
        run: bun run lint:oxlint && bun run lint:eslint

      - name: Run type check
        run: bun run type-check

      - name: Run formatting check
        run: bun run format

      - name: Build frontend
        run: bun run build
